apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: apic-pipeline-git
  namespace: ci
spec:
  encryptedData:
    GIT_PRIV_TOKEN: AgCX4Ax1w/aNYNixFX0CVmzDQjXshdc1i+OJc6AWbjm1swxkxqJfHnMlhWpe7cJ0U5hNtm9QrJmbRqgt1iHfZz0+Vo5fBz7ZWk5NgGbsrS+/qih/M9/7+UGwPPFxrZRFiyyXxbtULsQtmtjlGy5ybJunDfyOfdcAU6VBbA3nDsENLfbmOG0yuwj5YthecHDNZZ4jSkiT0Ay93cXl1Hme+XAMtxfE7gvis2ZpSXVuJ3XfUFEFxSVXedO3K6ViqEm+TeZczCZvwtdQj+IlMMTKVsfh3SMPUn0Yg42afrIps2ZrEwz74sCROQKl4297L9Uax/b4h67W7B9Yj/m4gefltCsLClTQMmmN8R+VAeZTKeMEbkaTkjsWphrFLju8R4yXacWXdHL2TN1Ljg6YyXsvYekTSrtbWSMFXthJ7dYYX3xUQ/sWqcTEEbYU30GK9U6bN+cT553GFMG0OOfQxklyu1Pex7g6VvRXiCgp6yL45eGxF0zoDdM84lRgQLL1HqgSq3xgPjptJfe2nFJazvjpXk8mV27S9RQzvvO/0JOOdg32gGeT/90oLab4RWJkvdsg05GLXiKKSv3D0gX/GSxCIr5oiTnHgkHR48gLc3+w25GZvPunxRyvgaF0hrDGvM410nOLR9jYQqr6SR6luHJwmRE7mZ2pqbcz+6OLCe5FVDhkRqxog2OClgVDheIkwxlSMhQt20MXsnXIZz2wyrHUwRSQ4u0NblXmujua5acwfK1czAxqAVYJcFjC
    GIT_USERNAME: AgBMFm9R/3+FWMhoYgUO3SW1hdx9C0B60gXyvJ3YSDFjaj8au9e3xs1y7eHKQxmGdBfrRtVVEhoHtqN/eeLCQQvLJcpO9YS48x232vyT+YceZFrmg7XxjccrPE9XZHXrAWkF640UO6O8q5WmWafdNYEwet7ibOaDHtwar+BhGhE6lrujMAAvq38ZPILIrSakzM8rCvenMKF9b8Lp9f34Dkm4yMNhy8/cbCOJZQvecr+5WnuVZtfjsN3IkFvgupTedHix+satiEhFuyCs9mGPn6T8VBLbGwj8o9a48kc0kGQqVRSjRFjYw1XNS25DQBb+C8L6F/YTHaXub9RcxvN+39GXPPN1f6pOVYfVUHoGOpHKM0sejSi//KpCnaAVzgK0wEzBDOp7Ki2U1Yp3paeCn1VrTRmAQp6HzKbXz8hVqiKpZ3tFEfADInFWtNF+xdlMa0PIYkBGHUCCnppA1KXxTVQphN/eEbhIaOAG5BtxKP24FHZ4UqdUuFHlqLgAIjTmAxNv5eIUWkgUZwqRG9Zy7WRjiOAbzm0clMq86c309eD0c9agV6oUkfGn+eo40hWHPRaj7MwMCQ/Mu3E4YmHuOztkzxP5RwZ1bRu/0kusHXt9o+HY6cfuldnWKyrUcNEqahz9fn5L0ed+ZQYWCQ0nZTMcT8BRnU/m02xerCQQ/VG4a7F3KGNqCe+vEJAjrgyh/eVXkpK6OSDZ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: apic-pipeline-git
      namespace: ci

